/* English dictionary (js/i18n_en.js) — Korean phrase -> English.
 * '#' stands for a number (kept in the same order). Longer phrases win over shorter ones.
 * Coverage: menus, labels, stats, positions, help, common templates. Event stories are translated step by step (see docs/i18n/README.md).
 * Add new lines freely; run `node tools/i18n_extract.cjs` to list Korean strings that still need translating. */
window.KL_I18N_EN={
/* ---- navigation / generic ---- */
"시즌":"Season","선수":"Player","커리어":"Career","소식":"News","닫기":"Close","확인":"OK","취소":"Cancel","뒤로":"Back","← 뒤로":"← Back","✕ 닫기":"✕ Close",
"게임 선택 메뉴":"Game menu","게임 선택 메뉴로":"Back to game menu","메인으로":"Back to main","홈으로":"Home","K-라이프 첫 화면":"K-LIFE start screen",
"이어하기":"Continue","새로운 인생 시작":"Start a new life","저장 삭제":"Delete save","도움말":"Help","도움말 · 능력치와 한계선":"Help · Stats & limits","📘 도움말 · 능력치와 한계선":"📘 Help · Stats & limits",
"설정":"Settings","패치노트":"Patch notes","라운지":"Lounge","슈팅 연습":"Shooting practice","축구 퀴즈":"Football quiz","축구 상식 퀴즈":"Football quiz","⚽ 축구 상식 퀴즈":"⚽ Football quiz","미니게임":"Mini-game",
"이벤트 도감":"Event log","📖 이벤트 도감":"📖 Event log","명예의 전당":"Hill of Fame","친구들 명예의 전당":"Friends' Hill of Fame","🏆 친구들 명예의 전당":"🏆 Friends' Hill of Fame",
"⚙ 설정 · 구단 이름과 로고":"⚙ Settings · Club names & logos","📰 패치노트 🔴 NEW":"📰 Patch notes 🔴 NEW","업데이트 예정":"Coming soon","불러오는 중…":"Loading…","불러오는 중":"Loading",
"나의 축구 인생은?":"What will your football life be?","이번 생, 어떤 선수로 살아볼까요?":"In this life, what kind of player will you be?","축구 인생 키우기":"Raise a football life",
"선수 만들기":"Create a player","스카우트 리포트":"Scout report","후보를 골라 주세요 ↑":"Puck a candidate ↑","이름을 먼저 적어 주세요 ↑":"Enter a name first ↑","훈련 방향을 골라 주세요 ↑":"Choose a training focus ↑","계약을 먼저 확정해 주세요 ↑":"Confirm the contract first ↑",
"다음 시즌으로":"Next season","다음 시즌":"Next season","오프시즌으로":"To the off-season","다음 해로":"To next year","시즌 결과 보기":"See season result","중반기 진행":"Play mid-season","후반기 진행":"Play late season","시즌 마무리 진행":"Finish the season","훈련 후 시즌 시작":"Train, then start the season",
"전반기":"Early season","중반기":"Mid-season","후반기":"Late season","시즌 마무리":"Season finale","프리시즌":"Pre-season","전반기 RESULT":"Early season RESULT","중반기 RESULT":"Mid-season RESULT","후반기 RESULT":"Late season RESULT","시즌 마무리 RESULT":"Season finale RESULT",
"전반기 · TRAINING RESULT":"Early season · TRAINING RESULT","중반기 · TRAINING RESULT":"Mid-season · TRAINING RESULT","후반기 · TRAINING RESULT":"Late season · TRAINING RESULT","시즌 마무리 · TRAINING RESULT":"Season finale · TRAINING RESULT",
"중반기 훈련 설정":"Mid-season training","후반기 훈련 설정":"Late-season training","시즌 마무리 훈련 설정":"Finale training","중반기 · #~#월":"Mid-season · months #–#","후반기 · #~#월":"Late season · months #–#","시즌 마무리 · #~#월":"Finale · months #–#","# 프리시즌 (#~#월)":"# Pre-season (months #–#)",
"#년 오프시즌":"# Off-season","# 시즌 결과":"# Season result","# 시즌 마무리":"# Season finale","# 중반기":"# Mid-season","# 후반기":"# Late season","#년을 준비해요":"Preparing for #",
/* ---- status / meters ---- */
"컨디션":"Condition","사기":"Morale","인기":"Fame","인성":"Character","평판":"Reputation","보유 자금":"Funds","연봉":"Salary","현재 연봉":"Current salary","최고 연봉":"Top salary","최저 연봉":"Lowest salary","구단 최고 연봉":"Club top salary","구단 최저 연봉":"Club lowest salary","계약 기간":"Contract length","소속":"Club","가정 환경":"Family background","가정환경":"Family background",
"⚪ 무명":"⚪ Unknown","🙂 평범한 프로":"🙂 Ordinary pro","🏘️ 지역구급":"🏘️ Local fame","🇰🇷 나라급":"🇰🇷 National fame","아직 알아보는 사람이 거의 없어요.":"Hardly anyone recognizes you yet.","동네에서는 알아보는 사람이 생겼어요.":"People in your neighborhood recognize you.","전국에서 이름이 알려졌어요.":"Your name is known nationwide.",
"· 다음 지역구급까지 #":"· # more to Local fame","· 다음 나라급까지 #":"· # more to National fame","· 다음 대륙급까지 #":"· # more to Continental fame","선택과 행동이 쌓여 인성 점수가 돼요. 광고 계약금과 평판에 영향을 줘요.":"Your choices add up to a character score. It affects endorsement fees and reputation.",
"컨디션 +#":"Condition +#","컨디션 -#":"Condition -#","사기 +#":"Morale +#","사기 -#":"Morale -#","인기 +#":"Fame +#","인기 -#":"Fame -#","평판 +#":"Reputation +#","감독 신뢰 +#":"Coach trust +#","감독 신뢰 -#":"Coach trust -#","자금 -#억":"Funds -#00M KRW",
"사기 +# · 인기 +#":"Morale +# · Fame +#","사기 +# · 컨디션 +#":"Morale +# · Condition +#","컨디션 +# · 사기 +#":"Condition +# · Morale +#","사기 -# · 컨디션 -#":"Morale -# · Condition -#","사기 +# · 감독 신뢰 +#":"Morale +# · Coach trust +#","사기 +# · 감독 신뢰 -#":"Morale +# · Coach trust -#","평판 +# · 사기 -#":"Reputation +# · Morale -#","평판 +# · 감독 신뢰 +#":"Reputation +# · Coach trust +#",
"사기 +# · 인기 -#":"Morale +# · Fame -#","컨디션 +# · 인기 -#":"Condition +# · Fame -#","사기 +# · 컨디션 +# · 인기 -#":"Morale +# · Condition +# · Fame -#","사기 +# · 인기 +# · 감독 신뢰 +#":"Morale +# · Fame +# · Coach trust +#","사기 +# · 자금 -#억":"Morale +# · Funds -#00M KRW",
/* ---- stats ---- */
"마무리":"Finishing","볼 다루기":"Ball control","질주력":"Pace","버티는 힘":"Strength","담력":"Composure","측면 창의력":"Wulg craft","연결 패스":"Passing","공간 읽기":"Vision","지구력":"Stamina","수비 감각":"Defending","대인 압박":"Tackling","후방 전개":"Build-up","선방":"Saving","순발력":"Reflexes","안정 캐칭":"Handling","발밑 킥":"Kicking","라인 통솔":"Command",
"마무리 훈련":"Finishing drill","볼 다루기 훈련":"Ball-control drill","질주력 훈련":"Pace drill","버티는 힘 훈련":"Strength drill","담력 훈련":"Composure drill","측면 창의력 훈련":"Wing-craft drill","휴식·회복":"Rest & recovery","미디어 활동":"Media work",
"근거리 마무리":"Close finishing","중장거리 슛":"Long-range shot","공중 장악":"Aerial control","볼 컨트롤":"Ball control","방향 전환":"Change of direction","압박 탈출":"Escaping pressure","최고 속도":"Top speed","순간 가속":"Burst","지치지 않는 질주":"Sprint endurance","몸싸움":"Physical duels","점프·타이밍":"Jump & timing","균형감":"Balance","결정적 순간 담력":"Big-moment nerve","일대일 해결":"One-on-one","압박 속 판단":"Decisions under pressure","킥 정확도":"Kick accuracy","크로스":"Crossing","패스 창의력":"Pass creativity","공간 인식":"Spatial awareness","템포 조절":"Tempo control","전환 판단":"Transition decisions","활동량":"Work rate","회복력":"Recovery","강도 유지":"Intensity","위치 선정":"Positioning","공간 커버":"Space cover","읽기·인터셉트":"Reading & intercepts","대인 마크":"Man-marking","태클 타이밍":"Tackle timing","투지":"Fighting spirit","후방 패스":"Back passes","전진 패스":"Forward passes","볼 소유 안정감":"Ball security","슈팅 선방":"Shot-stopping","일대일 방어":"One-on-one saves","위기 선방":"Crisis saves","반사 신경":"Reflexes","다이빙 범위":"Diving range","민첩성":"Agility","캐칭":"Catching","펀칭":"Punching","세컨드 볼 처리":"Second balls","골킥 거리":"Goal-kick distance","발밑 패스":"Short passing","빌드업 판단":"Build-up decisions","수비 조율":"Defensive organizing","공중볼 판단":"Aerial decisions","소통·리더십":"Communication & leadership",
"OVR":"OVR","최고 OVR":"Peak OVR","재능 예상":"Talent (est.)","나이":"Age","더 키울 수 있는 폭":"Room to grow","현재 잠재력":"Current potential","재능 게이지":"Talent gauge","잠재력":"Potential","재능":"Talent","재능 등급":"Talent grade","재능 개발 센터":"Talent Center","🌱 재능 개발 센터":"🌱 Talent Center",
/* ---- positions / roles ---- */
"공격수":"Forward","미드필더":"Midfielder","수비수":"Defender","골키퍼":"Goalkeeper","포지션":"Position","세부 포지션":"Specific position","스트라이커":"Striker","왼쪽 윙어":"Left winger","오른쪽 윙어":"Right winger","중앙 미드필더":"Central midfielder","공격형 미드필더":"Attacking midfielder","수비형 미드필더":"Defensive midfielder","센터백":"Centre-back","왼쪽 풀백":"Left-back","오른쪽 풀백":"Right-back",
"선호 역할":"Preferred role","주발":"Preferred foot","오른발":"Right foot","왼발":"Left foot","양발":"Both feet","정발":"Natural-side","역발":"Inverted","등번호 (비워 두면 자동)":"Shirt number (auto if empty)","선수 이름":"Player name","이름":"Name","체격 (비워 두면 포지션 평균)":"Build (position average if empty)","몸무게 kg":"Weight kg","키 cm":"Height cm",
"포처":"Poacher","타깃맨":"Target man","메짤라":"Mezzala","리베로":"Libero","스토퍼":"Stopper","스위퍼 키퍼":"Sweeper keeper","지휘형 골키퍼":"Commanding keeper","볼 플레잉 센터백":"Ball-playing centre-back","커버 센터백":"Covering centre-back","와이드 센터백":"Wide centre-back","노 논센스 센터백":"No-nonsense centre-back","박스 투 박스":"Box-to-box","볼 위닝 미드필더":"Ball-winning midfielder","딥라잉 플레이메이커":"Deep-lying playmaker","어드밴스드 플레이메이커":"Advanced playmaker","딥라잉 포워드":"Deep-lying forward","프레싱 포워드":"Pressing forward","올라운드 공격수":"All-round forward","어드밴스드 포워드":"Advanced forward","볼 플레잉 키퍼":"Ball-playing keeper","슈퍼 세이버":"Super saver","골라인 키퍼":"Goal-line keeper",
"골잡이형":"Finisher","돌파형":"Dribbler","타깃형":"Target type","크로스형":"Crosser","스토퍼형":"Stopper type","빌드업형":"Builder","선방형":"Shot-stopper","지휘형":"Commander","플레이메이커형":"Playmaker","박스 투 박스형":"Box-to-box","수비형 미드필더형":"Defensive midfielder","오버래핑 풀백형":"Overlapping full-back","스위퍼 키퍼형":"Sweeper keeper",
"공격수는 이런 자리예요":"What a forward does","미드필더는 이런 자리예요":"What a midfielder does","수비수는 이런 자리예요":"What a defender does","골키퍼는 이런 자리예요":"What a goalkeeper does","능력치와 역할":"Stats and roles","세부 포지션별 OVR 비중":"OVR weights by specific position","기본 비중 #%":"Base weight #%",
"OVR 비중 —":"OVR weights —","반대발(역발) 윙어는 —":"Inverted-foot winger —",
/* ---- grades / limits / help ---- */
"한계선: 어디까지 오를 수 있나요?":"Limits: how high can you go?","재능 등급 = OVR의 천장":"Talent grade = OVR ceiling","나이와 성장":"Age and growth","출전 대우 용어":"Playing-time terms","성장의 기본 규칙":"Basic growth rules","내 대우":"My status","현재 대우":"Current status",
"처음엔 몰라도 괜찮아요. 포지션과 능력치가 어떻게 OVR(종합 능력)이 되는지, 어디까지 오를 수 있는지를 한곳에 모았어요.":"No need to know it all at first. This page gathers how position and stats become OVR (overall) and how far you can grow.",
"잠재력은 능력치의 평균이 아니라 OVR이 도달할 수 있는 최대치예요. 개별 능력치는 99까지, OVR은 잠재력 이상으로는 거의 오르지 않아요.":"Potential is not an average of your stats; it is the maximum OVR you can reach. Single stats cap at 99 and OVR barely rises above your potential.",
"C급 #~# · B급 #~# · A급 #~# · S급 # 이상":"Grade C #–# · B #–# · A #–# · S # or more","C급 55~73 · B급 74~81 · A급 82~89 · S급 90 이상":"Grade C 55–73 · B 74–81 · A 82–89 · S 90+",
"등급은 #세 시즌이 끝날 때 확정돼요. 그 전에는 스카우터의 눈대중이에요.":"The grade is fixed when the age-# season ends. Until then it is only the scout's estimate.","재능 등급은 #세가 되면 확정되고":"The talent grade is fixed at age #",
"핵심 인재 · 핵심 주전 · 주전 · 로테이션 · 벤치 · #군":"Kiy prospect · Kiy starter · Starter · Rotation · Bench · Reserves","핵심 주전":"Kiy starter","주전":"Starter","로테이션":"Rotation","벤치":"Bench","핵심 인재":"Kiy prospect","차기 유망주":"Rising prospect","2군":"Reserves",
"낮은 능력치는 쉽게 오르고, 이미 높은 능력치는 더 어렵게 올라요. 트레이너 등급이 높을수록 높은 능력치도 잘 올라요.":"Low stats rise easily; high stats rise harder. Better trainers help even high stats grow.",
"컨디션이 낮거나 몸 관리를 소홀히 하면 성장이 둔해지고 부상 위험이 올라가요.":"Low condition or neglecting your body slows growth and raises injury risk.",
"약점 vs 강점 특훈":"Weakness vs strength drill","약점 보강 특훈":"Weakness drill","강점 특화 특훈":"Strength drill","집중 훈련":"Focused training","투자 안 함":"No investment","멘탈 코칭":"Mental coaching","메디컬 케어":"Medical care","비용 없음":"No cost",
"GOAT 각성":"GOAT awakening","GOAT의 문턱":"On the GOAT's threshold","황금빛 유혹":"Golden temptation",
/* ---- trainer ---- */
"트레이너 등급":"Trainer level","능력치가 높을수록 상위 트레이너가 필요해요":"Higher stats need higher-level trainers","하급 코치":"Basic coach","중급 전담 트레이너":"Mid-level trainer","상급 트레이너":"Senior trainer","최상급 트레이너":"Elite trainer","월드클래스 트레이너":"World-class trainer","무료":"Free","구간당 #만 원":"₩#0,000 per period","구간당 #억 원":"₩#00M per period",
/* ---- shop / money ---- */
"소비·후원":"Spending & sponsors","💸 소비·후원":"💸 Spending & sponsors","🛍 소비":"🛍 Shop","🧑‍💼 스태프":"🧑‍💼 Staff","📈 투자":"📈 Invest","🏅 명예":"🏅 Honors","자동차":"Cars","생활·기부":"Lifestyle & giving","구매":"Buy","보유":"Owned","고용":"Hire","해지":"Terminate","전부 팔기":"Sell all","원금":"Principal","작년":"Last year","투자 수익":"Investment returns","예금·국채":"Deposits & bonds","주식 ETF":"Stock ETF","가상자산":"Crypto","카페 창업":"Open a café","최소 #억 원":"Mon ₩#00M","투자할 자금이 부족해요":"Not enough funds to invest","자금이 부족해요":"Not enough funds","보유 자산":"Assets held",
"소비 · 후원":"Spending · Sponsors","광고 계약 중":"Endorsements","광고 제의":"Endorsement offers","광고 촬영":"Ad shoot","슬롯":"Slots","여러 개 고를 수 있어요":"You can choose several","수입 세단":"Imported sedan","스포츠카":"Sports car","국산 SUV":"Domestic SUV","전용기":"Private jet","페라리":"Sports supercar","람보르기니":"Exotic supercar","롤스로이스":"Luxury limousine","한강뷰 펜트하우스":"River-view penthouse","요트":"Yacht",
"개인 레슨":"Private lessons","해외 캠프":"Overseas camp","개인 기술 코치":"Personal skill coach","개인 요리사":"Personal chef","전담 의료팀":"Dedicated medical team","데이터 분석팀":"Data analysis team","홍보·SNS 팀":"PR & SNS team","프리미엄 에이전트":"Premium agent","프리미엄 회복 케어":"Premium recovery care","멘탈 코치":"Mental coach",
"자서전 출간":"Publish an autobiography","다큐멘터리 제작":"Make a documentary","개인 재단 설립":"Found a personal foundation","유소년 축구센터 설립":"Open a youth football center","구단 앞 동상 건립":"Statue outside the stadium","구단 인수 (구단주)":"Buy a club (owner)","소속 구단 지분 인수":"Buy a stake in your club",
/* ---- contract / transfer ---- */
"계약 수락":"Accept contract","재계약":"Contract renewal","재계약서":"Renewal contract","프로 계약서":"Pro contract","이적 계약서":"Transfer contract","임대 계약서":"Loan contract","재협상":"Renegotiate","재협상 (1회)":"Renegotiate (once)","서명하고 계약 확정":"Sign & confirm contract","지우기":"Clear","이전 사인 쓰기":"Use previous signature","다시 생각해 볼게요":"Let me think again","아래 칸에 손가락(또는 마우스)으로 사인해 주세요":"Sign in the box below with your finger (or mouse)","사인을 먼저 해 주세요":"Please sign first",
"이적 제의":"Transfer offers","임대 제의":"Loan offers","이적 시장":"Transfer market","OFFSEASON · 이적 시장":"OFFSEASON · Transfer market","현역 은퇴":"Retire","은퇴한다":"Retire","정말 은퇴할까요?":"Retire for real?","은퇴하면 되돌릴 수 없고, 은퇴 후의 삶으로 넘어가요.":"Retirement can't be undone. You move on to life after football.","조금 더 뛴다":"Play a bit longer",
"계약 완료: 연봉":"Contract done: salary","계약 기간":"Contract length","연봉 옵션 (선택)":"Salary options (optional)","달성 예상 #% · 보너스 #억":"Expected #% · Bonus ₩#00M","제시액":"Offer","보너스":"Bonus","원래 번호":"Original number","지금 번호":"Current number","어떤 등번호를 달까요?":"Which shirt number?","등번호를 바꿔야 해요":"You must change your number","SHIRT NUMBER":"SHIRT NUMBER",
"예상 역할":"Expected role","예상 역할 벤치":"Expected role: Bench","팀 전력":"Team strength","리그 평균":"League average","전력":"Strength","레전드리그#":"Legend League #","레전드리그# 최종 기록":"Legend League # final record","레전드리그# 우승":"Legend League # title","🏆 레전드리그# 우승":"🏆 Legend League # title",
"임대":"Loan","임대 복귀":"Loan return","병역":"Military service","현역 입대 (2년)":"Enlist (2 years)","병역 의무를 마쳤어요.":"You have completed military service.","체육요원":"Sports-service member","체육요원 복무 중이에요.":"You are serving as a sports-service member.","군 복무":"Military service","군필":"Served","미필":"Not served",
"2군 소속이에요":"You're in the reserves","2군에서 훈련하며 기회를 노린다":"Train in the reserves and wait for a chance","2부리그 임대":"Second-division loan","1군 호출":"First-team call-up","SQUAD ROLE":"SQUAD ROLE",
/* ---- season result ---- */
"순위표":"Table","득점왕":"Top scorers","도움왕":"Top assists","평점 1위":"Top rated","득실":"GD","승점":"Pts","승-무-패":"W-D-L","경기":"Games","승":"W","무":"D","패":"L","골":"Goals","도움":"Assists","출전":"Apps","평점":"Rating","결장":"Absent","우승":"Champions","승격":"Promoted","강등":"Relegated","최종 기록":"Final record","내 경기 기록 보기":"See my match log","▸ 내 경기 기록 보기":"▸ See my match log","밀어서 전체 보기":"Swipe for the full table","리그 순위":"League table",
"리그 우승":"League title","컵 우승":"Cup title","황금공":"Golden Ball","황금공 후보":"Golden Ball nominee","영구결번":"Retired number","월드컵":"World Cup","월드컵 우승":"World Cup winner","유럽 클럽컵":"European Club Cup","유럽 클럽컵2":"European Club Cup 2","유럽 클럽컵3":"European Club Cup 3","잉글랜드 1부 리그":"English top flight","스페인 1부 리그":"Spanish top flight","독일 1부 리그":"German top flight","이탈리아 1부 리그":"Italian top flight","프랑스 1부 리그":"French top flight","아시아 네이션스컵":"Asian Nations Cup","아시아 종합대회":"Asian Multi-Sport Games","종합 국제대회":"International Multi-Sport Games","전국컵":"National Cup","전국컵 #강":"National Cup R#","전국대회 #강":"National cup R#","유소년 리그":"Youth league","전국대회":"National tournament","주말리그":"Weekend league","대한민국":"South Korea","대표팀":"National team",
"🏆 우승 청부사":"🏆 Trophy winner","⭐ 스타 기질":"⭐ Star quality","🔥 노력의 천재":"🔥 Genius of effort","🛡️ 강철 체력":"🛡️ Arar body","🧩 만능 일꾼":"🧩 Utility man","✨ 천재":"✨ Prodigy",
"이번 시즌":"This season","올해 일정":"This year's schedule","🏟 올해 출전 대회:":"🏟 Competitions this year:","최근 소식":"Latest news","실시간 활동":"Live activity","시즌별 기록":"Season-by-season","프로 기록이 아직 없어요.":"No pro record yet.","커리어 평가":"Career rating","커리어 점수":"Career score","예상 등급":"Expected grade","통산":"Career","누적":"Total","전적":"Record","PRO CAREER":"PRO CAREER","통산 출전":"Career apps","수상":"Awards","리그우승":"League titles","컵우승":"Cup titles","대표팀 출전":"Caps",
/* ---- events / popups ---- */
"EVENT":"EVENT","SPENDING":"SPENDING","TALENT CENTER":"TALENT CENTER","CONFIRM":"CONFIRM","CONTRACT":"CONTRACT","CALL-UP":"CALL-UP","NATIONAL TEAM":"NATIONAL TEAM","CLUB LEGEND":"CLUB LEGEND","NOW ON SNS":"NOW ON SNS","SCOUT REPORT":"SCOUT REPORT","TRAINING RESULT":"TRAINING RESULT","CONTRACT · 재계약서":"CONTRACT · Renewal",
"안전한 선택":"Safe choice","안전한 선택 · 확정 (효과 #% · #% 확률로 작은 대가)":"Safe choice · guaranteed (#% effect · #% chance of a small cost)","안전한 선택 · 주사위 없이 확정 (효과 #%, #% 확률로 작은 대가)":"Safe choice · guaranteed without dice (#% effect, #% chance of a small cost)","🎲 주사위 # / 성공 기준 # → 성공":"🎲 Roll # / needs # → Success","🎲 주사위 # / 성공 기준 # → 실패":"🎲 Roll # / needs # → Failed","(작은 대가가 따라왔어요)":"(a small cost followed)",
"스토리":"Story","스토리 · 평생의 라이벌 #/#":"Story · Lifelong rival #/#","평생의 라이벌 #/#":"Lifelong rival #/#","평생의 라이벌 #/# · 만난 횟수 #회":"Lifelong rival #/# · Met # times","능력치가 변했어요":"Your stats changed","대회에 합류":"Join the tournament","불참한다 (인기·평판 하락)":"Decline (fame & reputation drop)","소집 불참":"Declined call-up","조 편성":"Group draw","개최지":"Host","조별리그 #차전":"Group stage match #","강팀":"strong","중위권":"mid-table","약체":"weak",
"트로피 받기":"Collect trophy","도전 시작":"Start the challenge","영광의 순간을 마친다":"Finish the moment","BEST ELEVEN":"BEST ELEVEN","베스트 11":"Team of the Year",
/* ---- cinematics ---- */
"건너뛰기 ›":"Skip ›","새로운 도전을 향해":"Toward a new challenge","입단!":"signed!","FLIGHT":"FLIGHT","WELCOME":"WELCOME","계약서":"CONTRACT","경기장 터널을 지나 그라운드에 들어서자 팬들의 함성이 쏟아져요.":"As you walk out of the tunnel, the crowd's roar pours over you.","프로 선수가 되다":"Becoming a pro","PRO DEBUT":"PRO DEBUT","태극마크를 달다":"Wearing the national badge","FIRST CALL-UP":"FIRST CALL-UP","유럽의 정상에 서다":"On top of Europe","트레블 달성!":"Treble won!","한계를 넘다":"Beyond the limit","재능이 눈을 뜨다":"Talent awakens","TALENT BREAKTHROUGH":"TALENT BREAKTHROUGH",
/* ---- talent center ---- */
"입소":"Enter","기본 재능 훈련":"Basic talent training","정밀 재능 코칭":"Precision coaching","해외 특별 코스":"Overseas special course","부담 없는 개인 지도":"Light private tutoring","전문 코치와 영상 분석":"Pro coaches with video analysis","유럽 아카데미 단기 과정":"Short course at a European academy","기본 성공":"Base success","성공 확률":"Success chance","잠재력 +#":"Potential +#","한계 돌파":"Limit break","1주차":"Week 1","2주차":"Week 2","마지막 주":"Final week","FINAL TEST":"FINAL TEST","지금!":"Now!","마지막 평가전! 움직이는 표시가 가운데 빛나는 칸에 올 때 눌러요.":"Final test! Tap when the moving marker is in the glowing middle zone.","이번 시즌에는 이미 입소했어요. 다음 시즌에 도전하세요.":"You already entered this season. Try again next season.",
/* ---- minigames ---- */
"① 슛 방향을 고르세요":"① Puck a shot direction","② 타이밍을 맞춰 슛!":"② Time your shot!","슛!":"Shoot!","표시가 가운데 칸에 있을 때 눌러요":"Press when the marker is in the middle zone","골~~~인!":"GOAL!!!","골키퍼가 막아냈어요!":"The keeper saved it!","슛이 골대를 벗어났어요!":"The shot missed the target!","벽에 막혔어요!":"Blocked by the wall!","골키퍼가 쳐냈어요!":"The keeper tipped it away!","크로스바를 넘어갔어요!":"Over the crossbar!","골문에 닿지 못했어요!":"It didn't reach the goal!","골문을 벗어났어요!":"Wide of the goal!","골~~~인! 환상적인 프리킥!":"GOAL! A fantastic free kick!",
"낮고 강하게":"Low & hard","높이 띄워 감기":"High & curled","공 근처에서 시작해 주세요":"Start near the ball","조금 더 길게 끌어당겨 주세요":"Drag a bit longer","그렇게는 찰 수 없어요. 앞으로 부드럽게 휘는 선만 가능해요":"You can't kick it like that. Only smooth forward curves work.","멀리·세게 끌수록 파워가 커지지만 정확도는 떨어져요. 지그재그 선은 인정되지 않아요.":"Dragging farther means more power but less accuracy. Zigzag lines don't count.","공에서 조준할 곳까지 쭉 끌어당기세요. 끌어당긴 선이 휘어 있으면 공도 그만큼 휘어 날아가요.":"Drag from the ball to your aim. If your line bends, the ball bends too.",
"페널티킥 찬스":"Penalty chance","프리킥 기회":"Free-kick chance","PENALTY KICK":"PENALTY KICK","FREE KICK":"FREE KICK","5번씩 차서 몇 골을 넣는지 겨뤄요. 최고 기록은 이 기기에 저장돼요.":"Take 5 kicks each and see how many you score. Your best is saved on this device.","⚽ 페널티킥 연습":"⚽ Penalty practice","🎯 프리킥 연습":"🎯 Free-kick practice","다시 하기":"Try again","메뉴로":"Menu","🎉 최고 기록 갱신!":"🎉 New best!","번째 킥":"th kick","실력":"Skill","초보":"Beginner","보통":"Normal","고수":"Expert",
/* ---- create / scout ---- */
"포인트":"Points","남은 포인트":"Points left","초기 포인트":"Starting points","재능":"Talent","가정환경":"Family","멘토":"Mentor","끈기":"Grit","건강":"Health","특성":"Trait","시작 시점":"Starting point","중학교 1학년 (13세 · U15)":"Middle school year 1 (age 13 · U15)","고등학교 입학 (16세 · U18)":"High school entry (age 16 · U18)","대학 졸업 신인 (#세)":"University graduate rookie (age #)","고교 졸업 신인 (#세)":"High-school graduate rookie (age #)","처음부터 긴 성장 스토리":"A long growth story from the start","🌱 처음부터 긴 성장 스토리":"🌱 A long growth story from the start","⚡ 바로 프로 도전":"⚡ Go pro right away","🔥 어려운 모드 · 가장 짧게":"🔥 Hard mode · shortest","가장 길게(#년) 키워요. 이야기가 가장 풍성해요.":"The longest path (# years). The richest story.",
"세 후보는 유형도, 체격도, 성장 여력도 서로 달라요. 지금 강한 선수가 끝까지 강하다는 보장은 없어요.":"The three candidates differ in type, build and growth potential. A strong player now isn't guaranteed to stay strong.","스카우터:":"Scout:","성장 여력이 아주 커 보여요":"Huge room to grow","몇 년 뒤가 기대되는 원석이에요":"A rough diamond worth watching","성장 여력이 괜찮은 편이에요":"Decent room to grow","노력하면 프로 주전까지는 충분해 보여요":"With effort, a pro starter looks realistic","평균적인 성장이 예상돼요":"Average growth expected","지금 모습 그대로 무난하게 클 것 같아요":"Likely to grow steadily as they are","성장 여력은 크지 않아 보여요":"Limited room to grow","타고난 재능보다 노력으로 승부해야 해요":"Woll need effort over raw talent",
"후보":"Candidate","스피드 괴물":"Speed monster","어린 날의 천재":"Child prodigy","대기만성형 거구":"Late-bloomer giant","올라운드 만능":"All-round","타고난 골잡이":"Born goalscorer","윙 테크니션":"Wulg technician","냉정한 승부사":"Cold-blooded competitor","경기 지휘관":"Match conductor","철벽 앵커":"Arar anchor","돌파하는 인사이드":"Driving inside man","지치지 않는 엔진":"Tireless engine","어린 날의 연출가":"Yealg playmaker","대기만성 박스형":"Late-bloomer box-to-box","만능 미드필더":"Utility midfielder","거친 수비벽":"Rough wall","빠른 풀백":"Fast full-back","빌드업 리베로":"Build-up libero","제공권 거인":"Aerial giant","영리한 조율사":"Clever organizer","대기만성 수비수":"Late-bloomer defender","반사신경 괴물":"Reflex monster","수비 지휘관":"Defensive commander","박스의 지배자":"Master of the box","안정적인 선방":"Reliable shot-stopper","대기만성 키퍼":"Late-bloomer keeper",
/* ---- misc UI ---- */
"배경음악":"Background music","백업 파일 저장":"Save backup file","백업 파일 불러오기":"Load backup file","설정 전체 초기화":"Reset all settings","구단 이름과 로고":"Club names & logos","로고 고르기":"Choose logo","닉네임":"Nickname","닉네임_없음":"no_nickname","잡담":"Chat","🐞 버그":"🐞 Bug","💡 아이디어":"💡 Idea","보내기":"Send","메시지를 입력해요 (120자)":"Type a message (120 chars)","링크·욕설은 올릴 수 없어요. 서로 존중해 주세요.":"Links and profanity aren't allowed. Please be respectful.",
"🌙 화면 테마 바꾸기":"🌙 Change theme","🌙 야간판(기존 어두운 화면)으로 바꾸기":"🌙 Switch to night theme","이 기기에만 저장돼요.":"Saved on this device only.","모바일에서 가장 잘 보이게 만들었어요.":"Designed to look best on mobile.","팬 프로젝트":"Non-profit fan project","게임 설명":"About","선수판":"Player mode","K-LIFE":"K-LIFE",
"전부":"All","없음":"None","예":"Yes","아니오":"No","완료":"Done","성공":"Success","실패":"Failed","진행 중":"In progress","최고":"Best","최저":"Lowest","평균":"Average","현재":"Now","다음":"Next","이전":"Previous","선택":"Select","변경":"Change","저장":"Save","삭제":"Delete","불러오기":"Load","새로고침권":"Refresh ticket","무료로 #장 받기":"Get # free","재도전":"Retry",
"억 원":"00M KRW","만 원":"0,000 KRW","억":"00M KRW","만":"0,000","년":" yr","세":" yrs old","개월":" months","시즌":"season","경기":"games","회":"×",
/* ---- league names / flags ---- */
"레전드리그1":"Legend League 1","레전드리그2":"Legend League 2","레전드리그":"Legend League","잉글랜드":"England","스페인":"Spain","독일":"Germany","이탈리아":"Italy","프랑스":"France","일본":"Japan","사우디아라비아":"Saudi Arabia","사우디":"Saudi","미국":"USA","브라질":"Brazil","카타르":"Qatar","중국":"China","이란":"Iran","이라크":"Iraq","바레인":"Bahrain","세네갈":"Senegal","우루과이":"Uruguay","콜롬비아":"Colombia","이집트":"Egypt","베트남":"Vietnam","인도네시아":"Indonesia","우즈베키스탄":"Uzbekistan","폴란드":"Poland","(가상)":"(fictional)",
"#부":"Division #","잉글랜드 #부":"England D#","스페인 #부":"Spain D#","독일 #부":"Germany D#","이탈리아 #부":"Italy D#","프랑스 #부":"France D#","일본 #부":"Japan D#","사우디 #부":"Saudi D#",
/* ---- injuries ---- */
"부상":"Injury","큰 부상":"Major injury","🩹 햄스트링 부상 #경기 결장":"🩹 Hamstring injury, out # games","🩹 허벅지 부상 #경기 결장":"🩹 Thigh injury, out # games","🩹 종아리 부상 #경기 결장":"🩹 Calf injury, out # games","🩹 갈비뼈 부상 #경기 결장":"🩹 Rib injury, out # games","🩹 발등 부상 #경기 결장":"🩹 Instep injury, out # games","🩹 무릎 인대 부상 #경기 결장":"🩹 Knee ligament injury, out # games","🩹 햄스트링 부상 — #경기 결장":"🩹 Hamstring injury — out # games","🩹 허벅지 부상 — #경기 결장":"🩹 Thigh injury — out # games","🩹 종아리 부상 — #경기 결장":"🩹 Calf injury — out # games","🩹 갈비뼈 부상 — #경기 결장":"🩹 Rib injury — out # games","🩹 발등 부상 — #경기 결장":"🩹 Instep injury — out # games","🩹 무릎 인대 부상 — #경기 결장":"🩹 Knee ligament injury — out # games",
"⚡ 집중 치료":"⚡ Intensive treatment","🛌 자연 회복":"🛌 Natural recovery","집중 치료":"Intensive treatment","자연 회복":"Natural recovery","남은 결장 #경기. 돈을 내면 최신 재활 치료로 #경기까지 줄일 수 있어요. 기다리면 무료지만 그만큼 못 뛰어요.":"# games left out. Pay for cutting-edge rehab to cut it to # games. Waiting is free but you miss more games.",
"세부:":"Details:","1군":"First team","2군 소속":"Reserve squad",
/* ---- quiz / misc buttons ---- */
"퀴즈 시작":"Start quiz","다시 도전":"Try again","정답":"Correct","오답":"Wrong","내 최고 기록:":"My best:","새로고침권 #장":"# refresh tickets",
"저장 중인 인생, 도감, 설정이 한 파일에 담겨요.":"Your saved life, log and settings go into one file.",
"아직 은퇴한 선수가 없어요.":"No retired players yet.","아직 만나지 못한 이벤트":"Events not yet met","지금까지 만난 이벤트 #/#":"Events met so far #/#","확률 도감 — 이벤트 규칙":"Odds guide — event rules",
"이상 징후":"Anomalies",
/* ---- main page ---- */
"교실 뒷자리 소년이 황금공의 주인공이 되기까지, 당신의 선택으로 써 내려가요":"From the back row of a classroom to a Golden Ball winner — written by your choices",
"이어하기 · ":"Continue · ","프리킥 · 페널티킥":"Free kicks · Penalties","친구들과 채팅 · 제보":"Chat with friends · Report","업데이트 내역":"Update history","구단 이름 · 로고 · 테마":"Club names · Logos · Theme",
"K-레전드는 레전드리그를 좋아하는 친구들이 만든 팬 게임이에요.":"K-Legend is a non-profit fan game made by friends who love football.","공개 기록을 바탕으로 한 추정 능력치로 승부해요.":"Ratings are estimates based on public records.",
"중학교 유소년부터 은퇴까지 한 선수의 인생을 키워요.":"Raise one player's whole life, from middle-school youth football to retirement.","황금공와 영구결번, 은퇴 후 감독·구단주 길까지 이어져요.":"It runs through Golden Ball, retired numbers and life as a manager or club owner after retirement.",
"선수판: 자녀 대회·유소년 시절 이야기, #부 이하 리그, 감독 성향 테스트, 프리킥·페널티 미니게임 확대":"Player mode: children's tournaments & youth stories, lower divisions, a coach-style test, more kick mini-games",
"선수판: 재능 개발 센터 연출 추가, 더 많은 역할별 능력치 세분화":"Player mode: more Talent Center scenes, more role-specific stats","라운지: 신고 기능, 닉네임 보호":"Lounge: report button, nickname protection",
"팬 프로젝트":"Non-profit fan project","선수 능력치는 공개 기록을 바탕으로 한 추정치예요.":"Player ratings are estimates based on public records.","모바일에서 가장 잘 동작해요.":"Works best on mobile.","영구결번 전시관":"Retired Numbers Gallery","HALL OF RETIRED NUMBERS":"HALL OF RETIRED NUMBERS","개 영구결번":"retired numbers","개 구단":"clubs","위 · 업적":"place · Achievements","업적":"Achievements","선수판 TOP 3":"Player mode TOP 3","커리어 점수 기준":"By career score","어려움 난이도":"Hard","내 선수가 없어요":"No players yet",
"오래 뛴 선수만이 보여 줄 수 있는 침착함.":"The calm only a long-serving player can show.","NO.":"No. ","영구결번":"retired number",
/* ---- player home ---- */
"중학교 유소년부터 은퇴까지. 훈련·계약·이적·국가대표·병역까지, 선택이 커리어를 바꿔요.":"From middle-school youth football to retirement. Training, contracts, transfers, national team, military service — your choices shape the career.",
"이번 생, 어떤 선수로 살아볼까요?":"In this life, what kind of player will you be?","NEW FOOTBALL LIFE":"NEW FOOTBALL LIFE","아직 은퇴한 선수가 없어요.":"No retired players yet.","한 번 나온 이벤트는 #구간 동안 다시 나오지 않아요":"A seen event won't repeat for # periods",
/* ---- season screen ---- */
"훈련 방향":"Training focus","훈련 설정":"Training setup","자기 투자":"Self-investment","가정 투자":"Family investment","가정 지원 투자":"Family support","구간마다":"each period","시즌 준비":"season prep","학년":"year","중학교":"Middle school","고등학교":"High school","대학교":"University","프로":"Pro","프로 #년차":"Pro year #","유소년":"Youth","드래프트":"Draft","드래프트 참가":"Enter the draft","대학 진학 (성장 후 재도전)":"Go to university (retry after growing)","해외 직행":"Go straight abroad","해외 유스":"Overseas youth","바로 프로 도전":"Go pro right away",
"방금 끝낸":"The one just finished","한 번 더 돌려요":"Replay it","부상이나 아쉬운 결과를 다시 시도할 수 있어요":"Retry after an injury or a disappointing result","다시 시도":"Retry",
"전반기 · TRAINING":"Early season · TRAINING","시즌 도중":"mid-season","이번 구간 빅매치":"Big match this period","큰 경기":"Big games","이벤트가 나올 확률":"Event chance",
/* ---- common sentence pieces ---- */
"예요.":".","이에요.":".","했어요.":".","해요.":".","돼요.":".","있어요.":".","없어요.":".","했어요":"","돼요":"",
"에 크게 반영돼요.":" strongly affects OVR.","이(가) OVR에 크게 반영돼요.":" strongly affect OVR.","OVR에는":"OVR uses","이(가) 가장 크게 반영돼요.":" the most.",
"스카우터의 눈대중이에요":"it's a scout's estimate","지금":"now","다음 시즌 예상":"next-season outlook","이대로 잔류하면":"if you stay","선발 확률 약":"starting chance about","(선발 확률 약 #%)":"(starting chance about #%)","· 이대로 잔류하면 다음 시즌 예상":"· Outlook next season if you stay",
"팀은 무승부로 끝났어요.":"The team drew.","팀 승리":"Team win","승리":"Win","패배":"Loss","무승부":"Draw"

};
